spring:
  profiles:
      active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: springcloud-config-dev
eureka:
  client:
    service-url:   # 监控页面
      defaultZone: http://yukicris1.com:7001/eureka/    
---
server:
  port: 8202
spring:
  profiles: test
  application: 
    name: springcloud-config-test
eureka:
  client:
    service-url:   # 监控页面
      defaultZone: http://yukicris1.com:7001/eureka/